#!/bin/bash

NAME=`echo $1 | sed 's/\.fg$//'`

if ! go build -o forge ./cmd/forge; then
	echo "Could not build Go compiler"
	exit 1
fi

if ! ./forge co -o bforge.c `find bootstrap -name '*.fg'`; then
	echo "Could not build bootstrap compiler"
	exit 1
fi

if ! gcc -o bforge bforge.c -I runtime; then
	echo "gcc failed to compile bforge.c"
	exit 1
fi

if ! ./bforge co -o ${NAME}.c $1; then
	echo "Exiting due to errors"
	exit 1
fi

if ! gcc -Wno-switch-enum -I ./runtime ${NAME}.c -o ${NAME}; then
	"gcc failed"
	exit 1
fi

./${NAME}
