package main

import (
	"fmt"
	goast "go/ast"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// funcEntry holds extracted info about a Go function or method.
type funcEntry struct {
	File      string
	Line      int
	Signature string
	DocLine   string
}

func scanGoFiles(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	var files []string
	for _, e := range entries {
		name := e.Name()
		if strings.HasSuffix(name, ".go") && !strings.HasSuffix(name, "_test.go") {
			files = append(files, name)
		}
	}
	sort.Strings(files)
	return files, nil
}

func isExported(name string) bool {
	return len(name) > 0 && name[0] >= 'A' && name[0] <= 'Z'
}

func exportName(name string) string {
	if len(name) == 0 {
		return name
	}
	return strings.ToUpper(name[:1]) + name[1:]
}

func formatSourceList(files []string) string {
	var quoted []string
	for _, f := range files {
		quoted = append(quoted, fmt.Sprintf("%q", f))
	}
	return strings.Join(quoted, ", ")
}

func buildSignature(fn *goast.FuncDecl, fset *token.FileSet) string {
	var b strings.Builder
	b.WriteString("func ")
	if fn.Recv != nil && len(fn.Recv.List) > 0 {
		recv := fn.Recv.List[0]
		b.WriteString("(")
		if len(recv.Names) > 0 {
			b.WriteString(recv.Names[0].Name)
			b.WriteString(" ")
		}
		b.WriteString(typeString(recv.Type))
		b.WriteString(") ")
	}
	b.WriteString(fn.Name.Name)
	if fn.Type.TypeParams != nil && len(fn.Type.TypeParams.List) > 0 {
		b.WriteString("[")
		b.WriteString(fieldListString(fn.Type.TypeParams))
		b.WriteString("]")
	}
	b.WriteString("(")
	if fn.Type.Params != nil {
		b.WriteString(fieldListString(fn.Type.Params))
	}
	b.WriteString(")")
	if fn.Type.Results != nil {
		results := fn.Type.Results.List
		if len(results) == 1 && len(results[0].Names) == 0 {
			b.WriteString(" ")
			b.WriteString(typeString(results[0].Type))
		} else if len(results) > 0 {
			b.WriteString(" (")
			b.WriteString(fieldListString(fn.Type.Results))
			b.WriteString(")")
		}
	}
	return b.String()
}

func fieldListString(fl *goast.FieldList) string {
	var parts []string
	for _, f := range fl.List {
		ts := typeString(f.Type)
		if len(f.Names) == 0 {
			parts = append(parts, ts)
		} else {
			var names []string
			for _, n := range f.Names {
				names = append(names, n.Name)
			}
			parts = append(parts, strings.Join(names, ", ")+" "+ts)
		}
	}
	return strings.Join(parts, ", ")
}

func typeString(expr goast.Expr) string {
	switch t := expr.(type) {
	case *goast.Ident:
		return t.Name
	case *goast.SelectorExpr:
		return typeString(t.X) + "." + t.Sel.Name
	case *goast.StarExpr:
		return "*" + typeString(t.X)
	case *goast.ArrayType:
		if t.Len == nil {
			return "[]" + typeString(t.Elt)
		}
		return "[" + exprString(t.Len) + "]" + typeString(t.Elt)
	case *goast.MapType:
		return "map[" + typeString(t.Key) + "]" + typeString(t.Value)
	case *goast.InterfaceType:
		if t.Methods == nil || len(t.Methods.List) == 0 {
			return "interface{}"
		}
		return "interface{...}"
	case *goast.FuncType:
		var b strings.Builder
		b.WriteString("func(")
		if t.Params != nil {
			b.WriteString(fieldListString(t.Params))
		}
		b.WriteString(")")
		if t.Results != nil {
			results := t.Results.List
			if len(results) == 1 && len(results[0].Names) == 0 {
				b.WriteString(" ")
				b.WriteString(typeString(results[0].Type))
			} else if len(results) > 0 {
				b.WriteString(" (")
				b.WriteString(fieldListString(t.Results))
				b.WriteString(")")
			}
		}
		return b.String()
	case *goast.Ellipsis:
		return "..." + typeString(t.Elt)
	case *goast.ChanType:
		switch t.Dir {
		case goast.SEND:
			return "chan<- " + typeString(t.Value)
		case goast.RECV:
			return "<-chan " + typeString(t.Value)
		default:
			return "chan " + typeString(t.Value)
		}
	case *goast.IndexExpr:
		return typeString(t.X) + "[" + typeString(t.Index) + "]"
	case *goast.IndexListExpr:
		var indices []string
		for _, idx := range t.Indices {
			indices = append(indices, typeString(idx))
		}
		return typeString(t.X) + "[" + strings.Join(indices, ", ") + "]"
	case *goast.StructType:
		return "struct{...}"
	case *goast.ParenExpr:
		return "(" + typeString(t.X) + ")"
	default:
		return fmt.Sprintf("<%T>", expr)
	}
}

func exprString(expr goast.Expr) string {
	switch e := expr.(type) {
	case *goast.BasicLit:
		return e.Value
	case *goast.Ident:
		return e.Name
	default:
		return "..."
	}
}

func buildFunctionIndex(funcs []funcEntry, sourceFiles []string) string {
	var b strings.Builder
	b.WriteString("// --- index ---\n")
	b.WriteString("//\n")
	b.WriteString("// Auto-generated function/method index with signatures in Go syntax.\n")
	b.WriteString("// DO NOT EDIT below this line — regenerated by `grok update`.\n")

	byFile := make(map[string][]funcEntry)
	for _, f := range funcs {
		byFile[f.File] = append(byFile[f.File], f)
	}

	for _, file := range sourceFiles {
		entries := byFile[file]
		b.WriteString("//\n")
		b.WriteString(fmt.Sprintf("// file: %s\n", file))
		for _, e := range entries {
			b.WriteString("//\n")
			if e.DocLine != "" {
				b.WriteString(fmt.Sprintf("// %s\n", e.DocLine))
			}
			b.WriteString(fmt.Sprintf("// %s    :%d\n", e.Signature, e.Line))
		}
	}
	b.WriteString("\n")
	return b.String()
}

func buildDependencies(imports map[string]bool, modPath string) string {
	if modPath == "" {
		return ""
	}
	var internal []string
	for imp := range imports {
		if strings.HasPrefix(imp, modPath+"/") {
			internal = append(internal, strings.TrimPrefix(imp, modPath+"/"))
		}
	}
	if len(internal) == 0 {
		return ""
	}
	sort.Strings(internal)

	var b strings.Builder
	b.WriteString("// --- dependencies ---\n")
	b.WriteString("//\n")
	b.WriteString("// Auto-generated internal package dependencies.\n")
	b.WriteString("// DO NOT EDIT below this line — regenerated by `grok update`.\n")
	b.WriteString("//\n")
	for _, dep := range internal {
		b.WriteString(fmt.Sprintf("// %s\n", dep))
	}
	return b.String()
}

func findModulePath(dir string) string {
	absDir, err := filepath.Abs(dir)
	if err != nil {
		return ""
	}
	for {
		data, err := os.ReadFile(filepath.Join(absDir, "go.mod"))
		if err == nil {
			for _, line := range strings.Split(string(data), "\n") {
				line = strings.TrimSpace(line)
				if strings.HasPrefix(line, "module ") {
					return strings.TrimSpace(strings.TrimPrefix(line, "module "))
				}
			}
		}
		parent := filepath.Dir(absDir)
		if parent == absDir {
			return ""
		}
		absDir = parent
	}
}
